spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smilegate_solo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: smilegate
    password: smilegate
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8082